[package]
name = "amd64_gen"
version = "0.1.0"
authors = ["Vlad Shcherbina <vlad.shcherbina@gmail.com>"]
edition = "2018"

[dev-dependencies]
binutils = { path = "../binutils" }

[lib]
doctest = false
