[package]
name = "binutils"
version = "0.1.0"
authors = ["Vlad Shcherbina <vlad.shcherbina@gmail.com>"]
edition = "2018"

[dependencies]
tempfile = "*"

[features]
clippy = []  # https://github.com/rust-lang/cargo/issues/8075

[lib]
doctest = false
