name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  schedule: [cron: "35 23 * * *"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  everything:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          rustup install nightly
          rustup default nightly
          rustup component add clippy
          cargo --version
          cargo clippy --version

      - uses: Swatinem/rust-cache@v2

      - run: cargo fetch --locked

      - run: cargo check

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: cargo test

      - run: cargo build --release --features=mimalloc

      - name: benchmark interpreter
        run: cargo run -p rusty_sand --release --features=mimalloc --bin main data/sandmark.umz --stats

      - name: benchmark JIT
        run: cargo run -p rusty_sand --release --features=mimalloc --bin main data/sandmark.umz --stats --jit
